export interface Data{
  projectName:          string;
  isFirstLaunch:        boolean;
  controller:           string;
  core:                 string;
  flashStart:           string;
  flashSizeHex:         string;
  flashSizeK:           string;
  flashPageSize:        string;
  ramStart:             string;
  ramEnd:               string;
  ramSizeK:             string;
  ramSizeHex:           string;
  stackSize:            string;
  heapSize:             string;
  startupFPU:           string;
  makefileFPU:          string;
  makefileFLOATABI:     string;
  standardC:            string;
  standardCPP:          string;
  optimization:         string;
  projectType:          string;
  svd:                  string;
  jlinkTaskDevice:      string;
  openocdTaskDevice:    string;
  openocdDevicePath:    string;
  openocdTransportPath: string;
  servertype:           string,
  debugger:             string,
  deviceInc:            string;
  includesDir:          string[];
  includes:             string[];
  sources:              string[];
  defines:              string[];
  flagsASM:             string[];
  flagsC:               string[];
  flagsCPP:             string[];
  interrupts:           string[];
}